name: zephy_client
description: Client to interact with Zephy server instances

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  adaptive_dialog: ^0.10.0+4
  auto_size_text_field: ^0.1.7
  crypt: ^3.0.1
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.3
  provider: ^4.3.2+1
  shared_preferences: ^2.0.5
  timeago: ^3.0.2
  widget_view: ^0.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
